python train.py \
  -dataset 'shapenet' \
  -category 'Airplane' \
  -level 1 \
  -fixed_points 1024 \
  -model 'vn_dgcnn_hmodel' \
  -embedding 6 \
  -k 20 \
  -margin 0.05 \
  -t_per_anchor 50 \
  -fraction 1.2 \
  -temperature 1 \
  -epochs 15 \
  -batch 6 \
  -lr 0.001 \
  -accelerator 'gpu'