python train.py \
  -dataset 'shapenet' \
  -category 'Chair' \
  -level 3 \
  -fixed_points 256 \
  -model 'vn_dgcnn_partseg' \
  -embedding 6 \
  -k 10 \
  -margin 0.05 \
  -t_per_anchor 50 \
  -temperature 1 \
  -epochs 50 \
  -batch 6 \
  -lr 0.005 \
  -accelerator 'gpu'