python train.py \
  --dataset 'shapenet' \
  --category 'Airplane' \
  --level 3 \
  --fixed_points 1024 \
  --model 'vn_dgcnn_partseg' \
  --eucl_embedding 32 \
  --hyp_embedding 32 \
  --k 20 \
  --margin 0.35 \
  --t_per_anchor 50 \
  --fraction 0.0 \
  --temperature 0.00 \
  --epochs 40 \
  --batch 2 \
  --lr 0.05 \
  --accelerator 'gpu' \
  --trade_off 0.10 \
  --resume 'liubigli-tcp/HPCS/runs/zu8e782y' \
  --infer \
#  --plot_inference