python train.py \
  -dataset 'shapenet' \
  -category 'Airplane' \
  -level 1 \
  -fixed_points 256 \
  -model 'vn_dgcnn_partseg' \
  -embedding 2 \
  -k 20 \
  -margin 0.05 \
  -t_per_anchor 50 \
  -fraction 1.2 \
  -temperature 1 \
  -epochs 20 \
  -batch 6 \
  -lr 0.005 \
  -accelerator 'gpu' \
  -trade_off 0.02