wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1660833497
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 77
      3:
      - 3
      - 16
      4: 3.7.13
      5: 0.12.21
      8:
      - 5
anneal:
  desc: null
  value: 1.0
anneal_step:
  desc: null
  value: 0
batch:
  desc: null
  value: 2
dataset:
  desc: null
  value: shapenet
embedding:
  desc: null
  value: 2
epochs:
  desc: null
  value: 1
factor:
  desc: null
  value: 0.5
fixed_points:
  desc: null
  value: 400
gpu:
  desc: null
  value: '0'
init_rescale:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.001
margin:
  desc: null
  value: 1.0
max_scale:
  desc: null
  value: 0.999
min_lr:
  desc: null
  value: 0.0001
min_scale:
  desc: null
  value: 0.01
model:
  desc: null
  value: dgcnn
nn:
  desc: null
  value: null
patience:
  desc: null
  value: 10
plot_every:
  desc: null
  value: -1
resume:
  desc: null
  value: false
sim_distance:
  desc: null
  value: cosine
temperature:
  desc: null
  value: 0.05
