wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1663677456.357622
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      3:
      - 3
      - 16
      - 23
      4: 3.10.4
      5: 0.13.2
      8:
      - 5
anneal:
  desc: null
  value: 1.0
anneal_step:
  desc: null
  value: 20
batch:
  desc: null
  value: 6
dataset:
  desc: null
  value: shapenet
dropout:
  desc: null
  value: 0.0
embedding:
  desc: null
  value: 4
epochs:
  desc: null
  value: 15
factor:
  desc: null
  value: 0.5
fixed_points:
  desc: null
  value: 1024
gpu:
  desc: null
  value: '0'
init_rescale:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.001
margin:
  desc: null
  value: 1.0
max_scale:
  desc: null
  value: 0.999
min_lr:
  desc: null
  value: 0.0001
model:
  desc: null
  value: vn_dgcnn_partseg
nn:
  desc: null
  value: null
patience:
  desc: null
  value: 10
pretrained:
  desc: null
  value: true
resume:
  desc: null
  value: false
sim_distance:
  desc: null
  value: cosine
temperature:
  desc: null
  value: 0.01
