wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1671124293.913287
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 3
      - 23
      4: 3.10.8
      5: 0.13.6
      8:
      - 5
anneal_factor:
  desc: null
  value: 2
anneal_step:
  desc: null
  value: 0
dataset:
  desc: null
  value: partnet
embedding:
  desc: null
  value: 18
fraction:
  desc: null
  value: 1.2
k:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
margin:
  desc: null
  value: 0.05
model_name:
  desc: null
  value: vn_dgcnn_partseg
nn:
  desc: null
  value: null
num_class:
  desc: null
  value: 18
t_per_anchor:
  desc: null
  value: 50
temperature:
  desc: null
  value: 1.0
test_rotation:
  desc: null
  value: so3
train_rotation:
  desc: null
  value: so3
